### ISSUE TITLE
mention anti-fingerprinting scope

### ISSUE THREAD

**Issue by jermanuts** [secureblue/hardened-chromium#105]
Anti-fingerprinting is out of this project's scope or not? I saw a lot of people asking whether this browser offers it or not.

https://github.com/secureblue/hardened-chromium?tab=readme-ov-file#scope

**Comment by RoyalOughtness** [comment]
"anti-fingerprinting" is "novel functionality that is unrelated to security", which is out of scope

**Comment by An-anonymous-coder** [comment]
> "anti-fingerprinting" is "novel functionality that is unrelated to security", which is out of scope

Wouldn't it fall under "Changes that disable opt-in metrics and data collection, so long as they have no security implications", since fingerprinting is used for data collection?

Browser fingerprinting I would argue even has direct security effect. Being able to cross reference user sessions across websites can be used to craft spear phishing attacks, and better tailor custom attacks or exploits if device hardware can be identified through browser fingerprinting. 

(Note: Trivalent does seem to spoof some hardware details such as the amount of system memory, but it may not be exhaustive.)

Privacy and security overlap in a lot of areas, and browser fingerprinting is one of them, especially since a lot of security is defined by your threat model. 

Not only should a browser protect you from digital security, but it should protect you from digital security as well. If you logged into a website that contains your personal details, such as your bank, you would **not** want that data (if it were to be leaked) to be linked back to the same browser you used to accidentally piss off someone on social media. That could put your physical security at risk. 

Again, "security" depends on your threat model, because it's "security from *what?*", but browser fingerprinting is something that should be taken into heavy consideration for a security focused browser.

**Comment by RKNF404** [comment]
@An-anonymous-coder 

> Wouldn't it fall under "Changes that disable opt-in metrics and data collection, so long as they have no security implications", since fingerprinting is used for data collection?

No, the browser does not fingerprint you for data collection purposes, websites do.

> Browser fingerprinting I would argue even has direct security effect.

Not really.

> Being able to cross reference user sessions across websites can be used to craft spear phishing attacks

Maybe, but users need to proactive when it comes to phishing. The best mitigation there is common sense... and disabling punycode.

> tailor custom attacks or exploits if device hardware can be identified through browser fingerprinting

Likelihood is they are just going to broad-stroke attempt attacks with or without fingerprinting mitigations if they have such an exploit. Or target users who *are* mitigating fingerprinting, since why would they hide their hardware otherwise? Little risk in trying.

> (Note: Trivalent does seem to spoof some hardware details such as the amount of system memory, but it may not be exhaustive.)

This is from upstream, I dont believe any of our nor Vanadium patches do this.

> Privacy and security overlap in a lot of areas, and browser fingerprinting is one of them, especially since a lot of security is defined by your threat model.

Not in this case, no. Fingerprinting is closer to anonymity. Which is far beyond privacy.
Not just that, it doesn't have any literal security benefit. What security issue(s) does it mitigate?

> Not only should a browser protect you from digital security, but it should protect you from digital security as well. If you logged into a website that contains your personal details, such as your bank, you would not want that data (if it were to be leaked) to be linked back to the same browser you used to accidentally piss off someone on social media. That could put your physical security at risk.

... I'm not sure how to respond to this. This person would need to hack that website (like your bank) in some way, either via xss or their servers. Even if that data is leaked, that usually just login credentials and the like, you should be gapping your online presences if this is a risk. That is *a lot* of effort. Efforts fingerprinting mitigations will not solve, since that is beyond the scope of the browser.

> Again, "security" depends on your threat model, because it's "security from what?"

This is defined in scope...

> but browser fingerprinting is something that should be taken into heavy consideration for a security focused browser.

... in which this is not. For this to be effective it takes a lot of research and time. Besides, there isn't much we can do. Most common place mitigations are not effective. I don't know if this will be the case forever, but at present fingerprinting is not in scope.

**Comment by An-anonymous-coder** [comment]
> No, the browser does not fingerprint you for data collection purposes, websites do.

The scope should probably clarify browser data collection in scope, rather than all data collection.

> This is from upstream, I dont believe any of our nor Vanadium patches do this.

Interesting.

> Not in this case, no. Fingerprinting is closer to anonymity. Which is far beyond privacy.

This gets lost in a lot of wordplay. By definition, privacy is the ability to control how your information is shared, and technically your browser fingerprint is part of your information. I understand what you mean, though.

> ... I'm not sure how to respond to this. This person would need to hack that website (like your bank) in some way, either via xss or their servers. Even if that data is leaked, that usually just login credentials and the like, you should be gapping your online presences if this is a risk. That is a lot of effort. Efforts fingerprinting mitigations will not solve, since that is beyond the scope of the browser.

The bank was just an example. It could be something like an online store sells your address and browser fingerprint, or other various scenarios. 

> For this to be effective it takes a lot of research and time. Besides, there isn't much we can do. Most common place mitigations are not effective.

There's really only two effective methods, as I'm sure we are all aware. I'll clarify anyways for anyone who may stumble on this:

One is k-anonymity, which is the Tor Browser's approach. It relies on making every user's fingerprint the same, so no user stands out from any other user. The downside of this is it relies on a large user base, and if even the slightest configuration is changed, a user is given a more unique fingerprint. That means it is not a flexible approach at all.

Another approach is randomizing everything, which is Brave Browser's approach. It randomizes as many non vital browser metrics as possible for each connection. This means that, for individual websites, the user is unique, but there is no way to track this user across sessions. This also means that configurations are much more flexible, since it gets drowned out with fake data. However, with advanced traffic analysis, a user can be deanonymized. 

Both have their pros and cons. Ideally the internet wouldn't rely on any browser metrics, but I think redoing the entire internet is a *bit* out of scope ;)

**Comment by RKNF404** [comment]
> The scope should probably clarify browser data collection in scope, rather than all data collection.

Fingerprinting isn't data collection. It is not the same as disabling telemetry.

> This gets lost in a lot of wordplay. By definition, privacy is the ability to control how your information is shared, and technically your browser fingerprint is part of your information. I understand what you mean, though.

Obscuring data is not the same as hiding it. That isn't control. If you want that, disable JavaScript and hardware acceleration.

> The bank was just an example. It could be something like an online store sells your address and browser fingerprint, or other various scenarios.

I know. But fingerprinting data isn't exactly the kind of thing to get exposed in a breach, it is still relatively niche when it comes to whats noteworthy compared to addresses or real names. But, how would this person obtain your fingerprint?

> k-anonymity

This is the only method that works, which unfortunately doesn't work for us here. It would take a lot of time and require a lot specifications. A lot of work for something that is very flimsy, yet effective.

> randomizing everything

Doesn't actually work, not in the proper sense. Brave's implementation does not work. It has gaps, lots of them. It, along with FF's RFP and FFP, only fool basic and low level fingerprinting, that which is basically not a threat anyways and would have zero effect on the security you are referring to.

> It randomizes as many non vital browser metrics as possible for each connection

No, it randomizes a few common elements like canvas and webgl. There are plenty of other metrics.

> the user is unique

No, they look like a user trying to look unique. This is a common misconception. You don't look like a random user, you look like a user trying to be random. This also neglects networking data, like IP address, DNS resolvers, etc.

> This also means that configurations are much more flexible, since it gets drowned out with fake data

No idea what this means.

> However, with advanced traffic analysis, a user can be deanonymized

Nothing to do with the browser.

> I think redoing the entire internet is a bit out of scope ;)

Just *a wee bit*... oy vey...

**Comment by RoyalOughtness** [comment]
> Privacy and security overlap in a lot of areas

They don't. Security is an industry standard concept with a clear meaning, privacy is nebulous and largely a marketing term.

> threat model

"threat modeling" is a term that gets gets thrown around without much respect to its meaning. Here's an introduction https://learn.microsoft.com/en-us/training/paths/tm-threat-modeling-fundamentals/

That said, please keep offtopic discussions like this to the discord.
