### ISSUE TITLE
Flatpak request

### ISSUE THREAD

**Issue by notmentaloutlaw** [secureblue/hardened-chromium#79]
Would it be possible to create a flatpak version of this browser for users to install? Something similar to how https://flathub.org/apps/org.chromium.Chromium is packaged. I am aware that the sandbox implementation of chromium on flatpak is no where as near as good as the native version. However, if its a simple task and there is interest then I would like to request one to be made. I personally use a flatpak version of chromium as the regular chromium can't be compiled against musl and firefox is honestly unusable.

**Comment by qoijjj** [comment]
Adding to what @RKNF404 said, you shouldn't be using any chromium based browser as flatpak, let alone this one, if you care about your browser's security. Flatpak interferes with the otherwise robust sandboxing mechanisms built into chromium

Flatpaking this project would be both out of scope and ironic, given the project's goals.

**Comment by notmentaloutlaw** [comment]
Then how about a statically linked chromium image? Would that work and be in the scope?

**Comment by qoijjj** [comment]
It's not something we're going to build and maintain, no. For any use outside secureblue we provide no official support.
